применяю гриды создаю адаптив
kellerov/NaturaShine pull request #2
Opened 2021-08-10 15:02 UTC by kellerov

2021-08-16 11:09 UTC, feerzlay requested changes
Еще пара замечаниий комментом:
- У карточек в "Хиты продаж" нужно убрать центрирование текста, убрать фиксированную высоту и расставить правильные отступы между элементами
- В этом же свайпере потерялась кнопка "влево"
- В ноушене писал про использование `<div class="container">`, думаю можно в этой ветке сделать

2021-08-16 11:09 UTC, feerzlay commented on src/scss/blocks/_catalog.scss
> +      @media #{$mobile} {
Нет особого смысла убирать `hover` эффект на мобилках, вижу тут много такого делается.

2021-08-16 11:09 UTC, feerzlay commented on src/scss/blocks/_header.scss
> +      grid-gap: 0 14px;
`grid-gap` считается deprecated, вместо него просто `gap`

2021-08-16 11:09 UTC, feerzlay commented on src/scss/blocks/_header.scss
> +        "header__logo menu"
`header__logo` можно назвать просто `logo`

2021-08-16 11:09 UTC, feerzlay commented on src/scss/blocks/_header.scss
> +        "menu__panel menu__panel";
Этот `menu__panel` выглядит лишним, он ведь вложен в `menu` и эта сетка на него никак не влияет.

2021-08-16 11:09 UTC, feerzlay commented on src/scss/blocks/_header.scss
> +      grid-area: header__bottom;
Так как он не в сетке находится, то это свойсто ничего и не делает.

2021-08-16 11:09 UTC, feerzlay commented on src/scss/blocks/_mailing.scss
> +.email > div {
Как раз отвечая на вопрос из чата. Лучше делать заводить отдельный класс. К слову тоже самое касается и инпута ниже.

2021-08-16 11:09 UTC, feerzlay commented on src/scss/blocks/_mailing.scss
> +  input[type="text"] {
Эти стили можно перенести в сам инпут.

2021-08-16 11:09 UTC, feerzlay commented on src/scss/blocks/_technologies.scss
> +    @media #{$mobile} {
Для красивого адаптива этот перенос стоит делать еще на планшете.

2021-08-16 11:09 UTC, feerzlay commented on src/scss/blocks/_technologies.scss
> +    @media #{$mobile} {
А вот этого лучше вообще не делать, карточка должна оставаться целой, в одну строку =)

2021-08-16 11:58 UTC, kellerov commented on src/scss/blocks/_catalog.scss
> +      @media #{$mobile} {
читал статью про адаптив там говорилось что это считается плохим тоном,и якобы необходимо убирать.

2021-08-16 12:03 UTC, kellerov commented on src/scss/blocks/_catalog.scss
> +      @media #{$mobile} {
в макете в хиты продаж не было кнопки влево изначально,  если я ничего не путаю..

2021-08-18 15:53 UTC, feerzlay commented
- Изображения в карточке через `img` заменены на `background-image`
- Контейнер с карточками сделан `flex`, чтобы сами карточки можно было растянуть по высоте 
- Отступ между карточками нужно сделать через `margin`
- Также "блоку с холодильником" изменены боковые внутренние отступы - 16 на планшете, 8 на мобильном 

Планшет:
- Ширина изображения 150px
![изображение](https://user-images.githubusercontent.com/13162449/129928331-71d8d78d-9162-4275-a902-5dfde012b295.png)
![изображение](https://user-images.githubusercontent.com/13162449/129928404-4a4db01c-f889-41da-b057-424334ec6cfb.png)

Мобильный:
- Ширина изображения 120px
![изображение](https://user-images.githubusercontent.com/13162449/129928686-6adca872-1235-43d2-b77e-c678df185716.png)
![изображение](https://user-images.githubusercontent.com/13162449/129928621-b487a23b-27b8-416c-b851-a0febb023bce.png)

2021-08-19 11:16 UTC, feerzlay commented on src/scss/blocks/_catalog.scss
> +      @media #{$mobile} {
Еще в стилях футера остался сброса ховера на мобильном

2021-08-19 11:31 UTC, feerzlay commented on src/scss/blocks/_mailing.scss
>  input[name="email"] {
Распишу новым комментом немного подробнее.  Эти cелекторы `input[type="text"]` и `input[name="email"]` стоит объединить в один и поместить внутрь блока `.email`, назвать например `&__input` (при этом существующий `&__input` переименовать во `&__wrapper`)

2021-08-19 14:30 UTC, merged